from .cleaning_plots import (
    plot_corrections,
    plot_critical_nan_drop,
    plot_current_nan,
    plot_dedup,
    plot_interpolation_recovery,
    plot_null_overview,
    plot_outlier_rates,
    plot_quality_invalidation,
    plot_retention_funnel,
    plot_validity_checks,
)
from .eda_plots import (
    plot_correlation_matrix,
    plot_monthly_precipitation_trend,
    plot_monthly_temperature_trend,
    plot_precipitation_distribution,
    plot_seasonal_temperature,
    plot_seasonal_wind,
    plot_station_coverage,
    plot_temperature_distribution,
    plot_temperature_heatmap_year_month,
    plot_top_stations_by_temperature,
    plot_wind_distribution,
    run_all_eda,
)

__all__ = [
    # cleaning plots
    "plot_null_overview",
    "plot_current_nan",
    "plot_dedup",
    "plot_critical_nan_drop",
    "plot_quality_invalidation",
    "plot_interpolation_recovery",
    "plot_retention_funnel",
    "plot_corrections",
    "plot_outlier_rates",
    "plot_validity_checks",
    # eda plots
    "plot_temperature_distribution",
    "plot_seasonal_temperature",
    "plot_precipitation_distribution",
    "plot_wind_distribution",
    "plot_monthly_temperature_trend",
    "plot_monthly_precipitation_trend",
    "plot_top_stations_by_temperature",
    "plot_correlation_matrix",
    "plot_temperature_heatmap_year_month",
    "plot_seasonal_wind",
    "plot_station_coverage",
    "run_all_eda",
]
